# Phase 1: Point Cloud 기초

이 노트북에서 배울 내용:
- Point Cloud란 무엇인가
- Open3D를 이용한 데이터 로딩/저장
- 기본 시각화
- 좌표 변환

In [4]:
# 라이브러리 임포트
import sys
sys.path.append('..')

import numpy as np
import open3d as o3d

from src.data import PointCloudLoader
from src.utils import Visualizer

## 1. Point Cloud란?

Point Cloud(점군)는 **3차원 공간의 점들의 집합**입니다.

각 점은 다음 정보를 가질 수 있습니다:
- **위치 (x, y, z)**: 필수
- **색상 (R, G, B)**: 선택
- **법선 벡터 (nx, ny, nz)**: 선택
- **강도 (Intensity)**: 선택 (LiDAR)

In [5]:
# 로더 초기화
loader = PointCloudLoader()

# 간단한 Point Cloud 직접 생성
points = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
])

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)

print(f"포인트 수: {len(pcd.points)}")
print(f"점 좌표:\n{np.asarray(pcd.points)}")

포인트 수: 4
점 좌표:
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2. 샘플 데이터 생성

In [6]:
# 박스 생성
box = loader.create_sample_box(center=(0, 0, 0.5), size=(1, 1, 1))
print("박스:", loader.get_info(box))

박스: {'포인트 수': 864, '최소 좌표': [-0.5, -0.5, 0.0], '최대 좌표': [0.5, 0.5, 1.0], '중심': [0.007011391086570385, -0.008861945975893674, 0.514391635408598], '색상 여부': True, '법선 여부': False}


In [7]:
# 구 생성
sphere = loader.create_sample_sphere(center=(2, 0, 0.5), radius=0.5)
print("구:", loader.get_info(sphere))

구: {'포인트 수': 1000, '최소 좌표': [1.5003744278981728, -0.49833465009848693, 0.0003171016949979899], '최대 좌표': [2.4984908122494103, 0.4999777803681349, 0.9996627154051485], '중심': [2.0031996372800576, 0.010558151017715558, 0.5130844357415858], '색상 여부': True, '법선 여부': False}


In [8]:
# 평면 생성
plane = loader.create_sample_plane(center=(0, 0, 0), size=(5, 5))
print("평면:", loader.get_info(plane))

평면: {'포인트 수': 2000, '최소 좌표': [-2.499295650372579, -2.4945910047021362, 0.0], '최대 좌표': [2.4987542015239885, 2.4993096326357946, 0.0], '중심': [-0.04189821043740563, -0.027842591997559327, 0.0], '색상 여부': True, '법선 여부': False}


## 3. 시각화

아래 셀을 실행하면 3D 뷰어가 열립니다.
- **마우스 좌클릭 드래그**: 회전
- **마우스 우클릭 드래그**: 이동
- **스크롤**: 줌
- **Q 또는 ESC**: 창 닫기

In [9]:
# 단일 Point Cloud 시각화
Visualizer.show(box, "Box Point Cloud")

In [10]:
# 여러 Point Cloud 함께 시각화
coord_frame = Visualizer.create_coordinate_frame(size=0.5)
Visualizer.show_multiple([box, sphere, plane, coord_frame], "Multiple Objects")

## 4. 샘플 씬 생성

In [11]:
# 바닥 + 여러 객체가 있는 씬
scene = loader.create_sample_scene(add_noise=True)
print("씬 정보:", loader.get_info(scene))

샘플 씬 생성: 5,316개 포인트
씬 정보: {'포인트 수': 5316, '최소 좌표': [-3.008700430231879, -2.9985738351279196, -2.8719327587207903], '최대 좌표': [3.0018101051810215, 2.9985003979173976, 2.9881681777786415], '중심': [-0.045805674834706135, -0.1743701538216375, 0.1583470418581985], '색상 여부': True, '법선 여부': False}


In [12]:
# 씬 시각화
Visualizer.show(scene, "Sample Scene")

## 5. 높이에 따른 색상 매핑

In [13]:
# 높이(Z)에 따라 색상 적용
scene_colored = Visualizer.colorize_by_height(scene, axis=2)
Visualizer.show(scene_colored, "Height Colored Scene")

## 6. 파일 저장/로드

In [14]:
# 저장
loader.save(scene, "../data/samples/sample_scene.ply")

# 로드
loaded = loader.load("../data/samples/sample_scene.ply")
print("로드된 데이터:", loader.get_info(loaded))

저장 완료: ../data/samples/sample_scene.ply
로드 완료: 5,316개 포인트
로드된 데이터: {'포인트 수': 5316, '최소 좌표': [-3.008700430231879, -2.9985738351279196, -2.8719327587207903], '최대 좌표': [3.0018101051810215, 2.9985003979173976, 2.9881681777786415], '중심': [-0.045805674834706135, -0.1743701538216375, 0.1583470418581985], '색상 여부': True, '법선 여부': False}
